name: Update data
on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:
permissions:
  actions: read
  checks: read
  contents: write
  deployments: read
  issues: read
  discussions: read
  pull-requests: read
  statuses: read
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: |
          deno run -A update.ts update
        env:
          GITHUB_TOKEN: ${{ github.token }}
